export const routePaths = {
  landing: '/',
  login: '/login',
  signup: '/signup',
  welcome: '/welcome',
  findId: '/find-id',
  resetPassword: '/reset-password',
  dashboard: '/dashboard',
  training: '/training',
  trainingCustomNew: '/training/custom/new',
  trainingSettings: '/training/:scenarioId/settings',
  trainingCall: '/training/:scenarioId/call',
  trainingResult: '/training/:scenarioId/result',
  records: '/records',
  community: '/community',
  notifications: '/notifications',
  profile: '/profile',
  profileEdit: '/profile/edit',
  profilePhoto: '/profile/photo',
  profileRingtone: '/profile/ringtone',
  profileNotifications: '/profile/notifications',
  profileLanguage: '/profile/language',
  profileDeleteAccount: '/profile/delete-account',
} as const
